#pragma config(Sensor, in1,    powerExpander,  sensorAnalog)
#pragma config(Sensor, dgtl1,  autonomousToggle, sensorDigitalIn)
#pragma config(Sensor, dgtl11, pistonLeft,     sensorDigitalOut)
#pragma config(Sensor, dgtl12, pistonRight,    sensorDigitalOut)
#pragma config(Motor,  port5,           driveSplitLeft, tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           driveSplitRight, tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"

void pre_auton(){
	bStopTasksBetweenModes = true;
}

void drive(int y, int t = 0, bool turbo=false){
	//y - Forwards/Backwards
	//t - Turning (optional parameter)
	//turbo - Switch to the turbo mode of the planetary transmission?
	motor[driveSplitLeft] 	= turbo ? y-t : y-t;
	motor[driveSplitRight] = turbo ? y+t : y+t;
}

int toggle_pistons(){
	int position = !SensorValue[pistonLeft];
	SensorValue[pistonLeft] = position;
	SensorValue[pistonRight] = position;
	return position;
}

int threshold(int value, int threshold){
	return abs(value)>threshold ? value : 0;
}

task autonomous(){
	//Checks if autonomous is enabled and should run
	//Don't run autonomous if the power expander has no battery, so we can touch it and replace it
	if(SensorValue[autonomousToggle]||!SensorValue[powerExpander]){return;}
	drive(-127);
	wait(3);
	drive(0);
}

task usercontrol(){
	int DY, DT;
	bool turbo = false;
	while(true){
		//Toggle turbo mode
		if(vexRT[Btn7U]){
			turbo = !turbo; //Flip the boolean
			waitUntil(!vexRT[Btn7U]);
		}
		//Toggle pistons
		if(vexRT[Btn7D]){
			toggle_pistons();
		}
		//Runs the code for driving the bot
		DY = threshold(vexRT[Ch2], 15);
		DT = threshold(vexRT[Ch1], 15);
		drive(DY, DT, turbo);
	}
}
