#pragma config(Sensor, in1,    powerExpander,  sensorAnalog)
#pragma config(Sensor, dgtl1,  autonomousToggle, sensorDigitalIn)
#pragma config(Sensor, dgtl11, pistonLeft,     sensorDigitalOut)
#pragma config(Sensor, dgtl12, pistonRight,    sensorDigitalOut)
#pragma config(Motor,  port2,           coneIntake,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveSplitLeft, tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           driveSplitRight, tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           liftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armRight,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"
#include "motion.c"
#include "utils.c"

void pre_auton(){
	bStopTasksBetweenModes = true;
}

task autonomous(){
	//Checks if autonomous is enabled and should run
	//Don't run autonomous if the power expander has no battery, so we can touch it and replace it
	if(SensorValue[autonomousToggle]||!SensorValue[powerExpander]){return;}
	drive(-127);
	wait(3);
	drive(0);
}

task usercontrol(){
	int DY, DT;
	bool armsLocked = false;
	while(true){
		//Driving
		DY = threshold(vexRT[Ch2], 15);
		DT = threshold(vexRT[Ch1], 15);
		drive(DY, DT);
		//Pistons (toggle)
		if(vexRT[Btn7R]){
			pistons(!PISTON_POS);
			waitUntil(!vexRT[Btn7R]);
		}
		//Arms
		if(vexRT[Btn7L]){
			armsLocked = !armsLocked;
			waitUntil(!vexRT[Btn7L]);
		}
		if(armsLocked){
			arms(ARM_LOCK);
		} else {
			arms((vexRT[Btn6U] - vexRT[Btn6D]) * MAX_POWER);
		}
		//Lift
		lift((vexRT[Btn7U] - vexRT[Btn7D]) * MAX_POWER);
		//Intake
		intake((vexRT[Btn5U] - vexRT[Btn5D]) * MAX_POWER);
	}
}
